#-------------------------------------------------------------------------#
#                                                                         #
#                 FUNCTIONS TO GENERATE MATHEMATICA FILES                 #
#                                                                         #
#-------------------------------------------------------------------------#

# V1 FECHA

#-------------------------------------------------------------------------#
# OBSERVACIONES:

# 1. Bla bla bla
# 2. Bla bla bla
# 3. Bla bla bla
#


# soatnuh -----------------------------------------------------------------



cat("\014") # borra consola 
rm(list=ls())  # Borra todo

# 1. Home
# 2. Work
# 3. Laptop
# 4. Other
rutas_prueba <- c("/Users/arrigocoen/Dropbox","/Users/useradmin/Dropbox","","")
eleccion_compu <- which(file.exists(rutas_prueba))

# Direcciones de cada computadora
source_raiz <- c("/Users/arrigocoen/Dropbox/1 How to/How-to-use-wolframscript",# 1. Home
                 "",# 2. Work
                 "",# 3. Laptop
                 "")[eleccion_compu]# 4. Other

setwd(source_raiz)


#-------------------------------------------------------------------------#

#' Generation of a .nb file in a specific folder with some text inside
#'
#' @param file_name name of the nb file
#' @param text_to_run text that will be printed inside the .nb file
#' @param add_print if it is needed that the extra text of Print[] is added
#' @param folder_nb_file folder where the .nb file will be saved
#'
#' @return
#' @export
#'
#' @examples
gen_nb_file <- function(file_name,text_to_run,folder_nb_file, add_print=T,add_date=T) {
  
  # text_to_run <- paste0(c("Print[\n",text_to_run,"\n]"))
  if(add_print) text_to_run <- paste0(c("Print[\n",text_to_run,"\n]"))
  if(add_date) nb_comments <- paste0(nb_comments,"\n Generated on ",format(Sys.time(), "%b %d %Y, at %X"),collapse = "")
  
  text_to_run <- paste0(c("(*\n",nb_comments,"\n*)\n\n",text_to_run,"\n"))
  file_name <- paste0(c(folder_nb_file,"/",file_name,".nb"),collapse = "")
  
  cat(text_to_run)
  # write.table(text_to_run, file=file_name, append = F, sep = "", dec = ".",row.names = F, col.names = F, quote = FALSE)
  cat("The file ",file_name," was generated\n")
}




text_to_run <- "Solve[{x == y - 13, y == 4 x + 234}]"
folder_nb_file <- "WLS_files_local"
file_name <- "Solving_equation_with_WS"
nb_comments <- "This is a .nb file generated by the function gen_nb_file\n Author: Arrigo Coen"
add_print= T

gen_nb_file(file_name,text_to_run,folder_nb_file, add_print=T)


# asoueth -----------------------------------------------------------------






text_to_run <- "Solve[{x == y - 13, y == 4 x + 234}]"
folder_nb_file <- "WLS_files_local"
file_name <- "Solving_equation_with_WS"
nb_comments <- "This is a .nb file generated by the function gen_nb_file\n Author: Arrigo Coen"
add_date <- T
add_print= T

if(add_date) nb_comments <- paste0(nb_comments,"\n Generated on ",format(Sys.time(), "%b %d %Y, at %X"),collapse = "")

text_to_run <- paste0(c("(*\n",nb_comments,"\n*)\n\n",text_to_run,"\n]"))
cat(text_to_run)



# asoueth -----------------------------------------------------------------






