#-------------------------------------------------------------------------#
#                                                                         #
#                 FUNCTIONS TO GENERATE MATHEMATICA FILES                 #
#                                                                         #
#-------------------------------------------------------------------------#

# V1 FECHA

#-------------------------------------------------------------------------#
# OBSERVACIONES:

# 1. Bla bla bla
# 2. Bla bla bla
# 3. Bla bla bla
#


# soatnuh -----------------------------------------------------------------



cat("\014") # borra consola 
rm(list=ls())  # Borra todo

# 1. Home
# 2. Work
# 3. Laptop
# 4. Other
rutas_prueba <- c("/Users/arrigocoen/Dropbox","/Users/useradmin/Dropbox","","")
eleccion_compu <- which(file.exists(rutas_prueba))

# Direcciones de cada computadora
source_raiz <- c("/Users/arrigocoen/Dropbox/1 How to/How-to-use-wolframscript",# 1. Home
                 "",# 2. Work
                 "",# 3. Laptop
                 "")[eleccion_compu]# 4. Other

setwd(source_raiz)
source("Functions.R")

# asnteuh -----------------------------------------------------------------






text_to_run <- "Solve[{x == y - 13, y == 4 x + 234}]"
folder_nb_file <- "WLS_files_local"
file_name <- "Solving_equation_with_WS"
nb_comments <- "This is a .nb file generated by the function gen_nb_file\n Author: Arrigo Coen"
add_print= T

gen_nb_file(file_name,text_to_run,folder_nb_file, add_print=T)


# asoueth -----------------------------------------------------------------




folder_nb_file <- "WLS_files_local"
file_to_copy <- "Solving_equation_with_WS.wls"
path_of_the_copied_file <-  "Folder_of_cluster"

copy_using_Terminal(file_to_copy,folder_nb_file,path_of_the_copied_file)



# astueh ------------------------------------------------------------------


terminal_command <- "wolframscript -code 2+2"

system(terminal_command)
# system("ls")


# asoteuh -----------------------------------------------------------------




text_to_run <- "Solve[{x == y - 13, y == 4 x + 234}]"
folder_nb_file <- "WLS_files_local"
file_name <- "Solving_equation_with_WS"
nb_comments <- "This is a .nb file generated by the function gen_nb_file\n Author: Arrigo Coen"
add_date <- T
add_print= T

if(add_date) nb_comments <- paste0(nb_comments,"\n Generated on ",format(Sys.time(), "%b %d %Y, at %X"),collapse = "")

text_to_run <- paste0(c("(*\n",nb_comments,"\n*)\n\n",text_to_run,"\n]"))
cat(text_to_run)



# asoueth -----------------------------------------------------------------

folder_files_wls <- "Folder_of_cluster"
wls_file_to_run <- "Solving_equation_with_WS.wls"
output_name <- "output_Solving_equation_with_WS.txt"
rut_Terminal_using_R(folder_files_wls, wls_file_to_run, output_name)



# Extra stuff -------------------------------------------------------------



Following this methodology we should get a `.txt`file like this:
  ![Test Image 1](Fig_error.png)

Questions and/or corrections about this repository are more than welcome! please send them to coencoria@wisc.edu 


# Stuff to erase



First, I can't use wolframscript at the terminal, since I get the message
 
![Test Image 1](Fig_error.png)

So.... lets fix this!

## Dowload Wolframscript

Go to the page:
[https://reference.wolfram.com/language/workflow/InstallWolframScript.html](https://reference.wolfram.com/language/workflow/InstallWolframScript.html)

Examples of how to use wolframscript 
[https://reference.wolfram.com/language/ref/program/wolframscript.html](https://reference.wolfram.com/language/ref/program/wolframscript.html)

An example of wolframscript on terminal
>>> wolframscript -code 2+2



wolframscript -script test.m
math -script test.m



This option do somethin
>>> cd "/Users/arrigocoen/Dropbox/1 How to/How-to-use-wolframscript"
>>> wolframscript -script test.m

If i run 
>>> wolframscript -script test.m &> out_test.txt; 
I get a txt with the message of the error,
even if I add the line 
$Pre = Quiet
to the .nb file 

Remember that you need to initialize the cell and to save the file as .m (use save as for this last part)

wolframscript -script test2.m &> out_test.txt; 

wolframscript -file test2.wls



wolframscript -script test4.wls > out_test4.txt



Copiando archivos de local al cluster

cd "/Users/arrigocoen/Dropbox/1 How to/How-to-use-wolframscript"

scp test4.wls acoencoria@solislemus-001.discovery.wisc.edu:/mnt/dv/wid/projects1/SolisLemus-ArrigoCC/

/Users/arrigocoen/Dropbox/1 How to/How-to-use-wolframscript


% More about of copy the output in https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file


# saoueh ------------------------------------------------------------------










